/**
 * Created by newuser on 2018/11/20.
 */
export const RECEVIVE_DATA = 'RECEVIVE_DATA'
export const SHOW_BOOKSHELF = 'SHOW_BOOKSHELF '
export const SHOW_SEARCH = 'SHOW_SEARCH'
export const SHOW_CLASSIFY = 'SHOW_CLASSIFY'
export const SHOW_CDETAIL = 'SHOW_CDETAIL'
export const SHOW_PANK = 'SHOW_PANK'
export const SHOW_WOMEN = 'SHOW_WOMEN'
export const SHOW_MAN = 'SHOW_MAN'
export const SHOW_BOOKLIST = 'SHOW_BOOKLIST'
export const SHOW_PERSONAL = 'SHOW_PERSONAL'
export const SHOW_DETAILS = 'SHOW_DETAILS'
export const SHOW_BLIST = 'SHOW_BLIST'
export const SHOW_DVIEW = 'SHOW_DVIEW'
export const SHOW_WDETAIL = 'SHOW_WDETAIL'
export const SHOW_MDETAIL = 'SHOW_MDETAIL'
export const SHOW_CCDETAIL = 'SHOW_CCDETAIL'

export const RECEVIVE_GIRL = 'RECEVIVE_GIRL'
export const RECEVIVE_BOY = 'RECEVIVE_BOY'
export const RECEVIVE_NEWBOOK = 'RECEVIVE_NEWBOOK'
export const RECEVIVE_AUTHER = 'RECEVIVE_AUTHER'
export const RECEVIVE_BOOKSHELF = 'RECEVIVE_BOOKSHELF'
export const RECEVIVE_UPDATA = 'RECEVIVE_UPDATA'
export const RECEVIVE_BOOKDATE = 'RECEVIVE_BOOKDATE'
export const RECEVIVE_CLASSIFY = 'RECEVIVE_CLASSIFY'
export const RECEVIVE_BOOKLISTDATA = 'RECEVIVE_BOOKLISTDATA'
export const PUSHSHELF = 'PUSHSHELF'
export const DELETE_SHELF = 'DELETE_SHELF'
export const WDETAILS = 'WDETAILS'
export const MDETAILS = 'MDETAILS'
export const CDETAILS = 'CDETAILS'
export const SET_BOOK_INFO = 'SET_BOOK_INFO'
export const SET_INDEX = 'SET_INDEX'



